### ISSUE TITLE
Augmentation of less represented heights

### ISSUE THREAD

**Issue by luciapapalini** [djanloo/cmepda#11]
Some of the "heights" are less represented in the dataset, maybe to improve the net's performances we need to augment them

**Comment by luciapapalini** [comment]
My soul wants to augment even more those at higher heights, could we augment with a threshold on the height?

**Comment by djanloo** [comment]
@luciapapalini  at the moment data are selected conditionally on the FeederProf score estimation, that suggests a possible "uneven" data augmentation. 
I think doing as you suggested would be preferable. It shouldn't take long.

**Comment by luciapapalini** [comment]
It works well for both height threshold and difficulty threshold
